version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docusaurus:
        applies-to: version-updates
        patterns: "@docusaurus/*"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      program-dependencies:
        applies-to: version-updates
        dependency-type: production
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
